# Generated by Django 4.0.5 on 2022-06-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='btn_text',
            field=models.CharField(default='bar', max_length=30),
        ),
        migrations.AddField(
            model_name='phase',
            name='ref',
            field=models.CharField(default='foo', max_length=20),
        ),
    ]
