# Generated by Django 4.0.5 on 2022-07-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='as', upload_to=''),
            preserve_default=False,
        ),
    ]
