# Generated by Django 4.0.5 on 2022-07-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_post_created_date_post_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='image',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_date',
        ),
    ]
