# Generated by Django 4.0.5 on 2022-07-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_image_certificate_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='url',
        ),
    ]
